api:
  port: 8080
  poc_callback_url: http://localhost:8080
  public_url: http://localhost:8080
nodes:
  - id: node1
    host:  34.171.235.205 # Deployed inference node
    inference_port: 8080
    poc_port: 5000
    max_concurrent: 500
    models:
      - Qwen/Qwen2.5-7B-Instruct
chain_node:
  url: http://node:26657
  account_public_key: ""
  signer_key_name: "alice"
  keyring_backend: "test"
  keyring_dir: "/root/.inference"
  is_genesis: false
