apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
  labels:
    app: node
spec:
  serviceName: "node"
  replicas: 1 # Typically 1 for a specific join node identity
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      enableServiceLinks: false
      imagePullSecrets: # Add if your image is in a private registry
      - name: ghcr-credentials
      containers:
      - name: node
        image: node
        imagePullPolicy: IfNotPresent
        command:
        - "sh"
        - "-c"
        - "./init-docker.sh" # Assuming this script is in the image's WORKDIR/PATH
        ports:
        - containerPort: 26656
          name: tendermint-p2p
        - containerPort: 26657
          name: tendermint-rpc
        - containerPort: 26658
          name: tmkms
        - containerPort: 1317
          name: rest-api
        - containerPort: 9090
          name: tendermint-grpc
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: SEED_NODE_RPC_URL
          value: "http://34.9.136.116:30002"
        - name: SEED_NODE_P2P_URL
          value: "tcp://34.9.136.116:30001"
        - name: RPC_SERVER_URL_1
          value: "http://34.9.136.116:30002"
        - name: RPC_SERVER_URL_2
          value: "http://34.9.136.116:30002"
        - name: SNAPSHOT_INTERVAL
          value: "1000"
        - name: SNAPSHOT_KEEP_RECENT
          value: "5"
        - name: TRUSTED_BLOCK_PERIOD
          value: "2000"
        - name: CONFIG_p2p__allow_duplicate_ip
          value: "true"
        - name: CONFIG_p2p__handshake_timeout
          value: "30s"
        - name: CONFIG_p2p__dial_timeout
          value: "30s"
        - name: TKMS_PORT
          value: "26658"
        - name: TMKMS_PORT
          value: "26658"
        - name: REST_API_ACTIVE
          value: "true"  # Enable REST API server for explorer
        volumeMounts:
        - name: inference-data
          mountPath: /root/.inference # Shared data with API
      volumes:
      - name: inference-data # This volume is now a hostPath
        hostPath:
          path: /srv/dai/inference # Matches genesis setup
          type: DirectoryOrCreate
