apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  type: NodePort
  selector:
    app: node
  ports:
  - name: tendermint-p2p
    port: 26656
    targetPort: 26656
    nodePort: 30021
  - name: tendermint-rpc
    port: 26657
    targetPort: 26657
    nodePort: 30022
  - name: tmkms
    port: 26658
    targetPort: 26658
  - name: rest-api
    port: 1317
    targetPort: 1317
    nodePort: 30023
  - name: grpc
    port: 9090
    targetPort: 9090
    nodePort: 30024
