name: Unit Tests (Local)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests-local:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pip install --upgrade poetry

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.cache/pypoetry
            /home/runner/.cache/pip
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Prepare .env
        run: |
          make setup-envs
          sed -i 's#CACHE_DIR=<CACHE_DIR>#CACHE_DIR=/tmp/cache_dir#g' .env

      - name: Install local dependencies
        run: make setup-dev-env

      - name: Run unit-tests-local
        shell: bash
        run: |
          source .venv/bin/activate
          make unit-tests-local
