apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-overrides-cm
data:
  genesis_overrides.json: |
    {
      "app_state": {
        "gov": {
          "params": {
            "voting_period": "4m0s",
            "min_deposit": [
              {
                "denom": "ngonka",
                "amount": "25_000_000"
              }
            ],
            "expedited_voting_period": "2m0s",
            "expedited_min_deposit": [
              {
                "denom": "ngonka",
                "amount": "50_000_000"
              }
            ],
            "quorum": "0.00010000000000000"
          }
        },
        "inference": {
          "params": {
            "epoch_params": {
              "epoch_length": "250",
              "epoch_multiplier": "1",
              "epoch_shift": "230",
              "inference_validation_cutoff": "25",
              "poc_stage_duration": "50",
              "poc_exchange_duration": "5",
              "poc_validation_delay": "5",
              "poc_validation_duration": "20",
              "set_new_validators_delay": "25",
              "default_unit_of_compute_price": "100"
            },
            "tokenomicsParams": {
              "subsidy_reduction_interval": {
                "value": "5",
                "exponent": -2
              },
              "subsidy_reduction_amount": {
                "value": "2",
                "exponent": -1
              },
              "current_subsidy_percentage": {
                "value": "1",
                "exponent": -1
              },
              "top_reward_allowed_failure": {
                "value": "1",
                "exponent": -1
              },
              "top_miner_poc_qualification": "10"
            }
          },
          "model_list": [
            {
              "proposed_by": "genesis",
              "id": "Qwen/Qwen2.5-1.5B-Instruct",
              "units_of_compute_per_token": "75",
              "hf_repo": "Qwen/Qwen2.5-1.5B-Instruct",
              "hf_commit": "976055f8c83f394f35dbd3ab09a285a984907bd0",
              "model_args": [],
              "v_ram": "16",
              "throughput_per_nonce": "10000",
              "validation_threshold": {
                "value": "85",
                "exponent": -2
              }
            },
            {
              "proposed_by": "genesis",
              "id": "Qwen/Qwen2.5-7B-Instruct",
              "units_of_compute_per_token": "100",
              "hf_repo": "Qwen/Qwen2.5-7B-Instruct",
              "hf_commit": "a09a35458c702b33eeacc393d103063234e8bc28",
              "model_args": [
                "--quantization",
                "fp8"
              ],
              "v_ram": "16",
              "throughput_per_nonce": "10000",
              "validation_threshold": {
                "value": "85",
                "exponent": -2
              }
            }
          ],
          "genesis_only_params": {
            "total_supply": "1000000000000000000",
            "originator_supply": "160000000000000000",
            "top_reward_amount": "120000000000000000",
            "standard_reward_amount": "600000000000000000",
            "pre_programmed_sale_amount": "120000000000000000",
            "top_rewards": 3,
            "supply_denom": "ngonka"
          }
        }
      }
    }
