apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Changed 'bases:' to 'resources:' to include the common kustomization
resources:
- ../common

- config.yaml
- genesis-overrides-configmap.yaml

# Workloads specific to Genesis
- node-statefulset.yaml
- api-deployment.yaml
- inference-deployment.yaml
- inference-deployment-2.yaml
- proxy-service.yaml
- node-service.yaml

components:
- ../image-versions
