[tool.poetry]
name = "mlnode-pow"
version = "0.1.0"
description = "MLNode pow package"
authors = [
    "Gleb Morgachev <gleb.morgachev@productscience.ai>",
    "Tamaz Gadaev <tamaz@productscience.ai>",
    "Egor Shulgin <egor.shulgin@productscience.ai>"
]
packages = [{include = "pow", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.4.1"
pydantic = "^2.9.2"
scipy = "^1.14.1"
numpy = "^2.1.1"
tiktoken = "^0.8.0"
fire = ">=0.7.0"
tqdm = ">=4.66.0"
fastapi = ">=0.115.8"
uvicorn = ">=0.34.0"
accelerate = ">=0.26.0"
mlnode-common = { path = "../common", develop = true }

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-timeout = "^2.3.1"
ruff = "^0.6.9"
wait-for-it = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
